Repository rambunction4330/RobotCode2022, pull requests merged in 2022-02, with the labels that each got.

#72 Drive subsystem functions
  lib/include/rmb/drive/HolonomicDrive.h
  lib/src/drive/HolonomicDrive.cpp
  src/main/cpp/drivetrain/DriveSubsystem.cpp
  src/main/include/drivetrain/DriveSubsystem.h
Labels: enhancement

#94 add spinOffset
  lib/include/rmb/motorcontrol/sparkmax/SparkMaxPositionController.h
  lib/src/motorcontrol/sparkmax/SparkMaxPositionController.cpp
Labels: enhancement

#99 Possible solution to issues with commands
  lib/include/rmb/command/RepeatingCommand.h
  lib/include/rmb/command/SelfManagedCommand.h
  lib/src/command/SelfManagedCommand.cpp
Labels: enhancement

#96 Doxygen Implementation
  lib/include/rmb/drive/MecanumEncoderOdometry.h
  lib/include/rmb/motorcontrol/PositionController.h
  lib/include/rmb/motorcontrol/VelocityController.h
  lib/include/rmb/motorcontrol/feedforward/ArmFeedforward.h
  lib/include/rmb/motorcontrol/feedforward/ElevatorFeedforward.h
  lib/include/rmb/motorcontrol/feedforward/Feedforward.h
  lib/include/rmb/motorcontrol/feedforward/SimpleMotorFeedforward.h
Labels: documentation, enhancement, help wanted, wontfix, sus

#107 Update doxygen-publish.yml to build off of main
  .github/workflows/doxygen-publish.yml
Labels: bug, documentation
